### PR TITLE
Fix build on Ubuntu

### LINKED ISSUE #9: Fix Homebrew Ubuntu Integration
For further information see: https://github.com/drogonframework/homebrew-drogon/pull/5

### PR DESCRIPTION
**Pull request by ken-matsui**
Fixes https://github.com/drogonframework/homebrew-drogon/issues/9

### CODE REVIEW

**Comment by ken-matsui** [comment]
```
-- Found UUID: /home/linuxbrew/.linuxbrew/lib/libuuid.so
CMake Error at CMakeLists.txt:248 (message):
  uuid lib error
```

**Comment by ken-matsui** [comment]
```console
Building CXX object CMakeFiles/cmTC_00946.dir/ossp_uuid_lib_test.cc.o


  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++-13
  -isystem /usr/include/uuid -o
  CMakeFiles/cmTC_00946.dir/ossp_uuid_lib_test.cc.o -c
  /tmp/drogon-20230824-6746-jd94ug/cmake/tests/ossp_uuid_lib_test.cc

  /tmp/drogon-20230824-6746-jd94ug/cmake/tests/ossp_uuid_lib_test.cc: In
  function 'int main()':

  /tmp/drogon-20230824-6746-jd94ug/cmake/tests/ossp_uuid_lib_test.cc:5:5:
  error: 'uuid_create' was not declared in this scope; did you mean
  'uuid_clear'?

      5 |     uuid_create(&uuid);
        |     ^~~~~~~~~~~
        |     uuid_clear

  /tmp/drogon-20230824-6746-jd94ug/cmake/tests/ossp_uuid_lib_test.cc:6:21:
  error: 'UUID_MAKE_V1' was not declared in this scope

      6 |     uuid_make(uuid, UUID_MAKE_V1);
        |                     ^~~~~~~~~~~~

  /tmp/drogon-20230824-6746-jd94ug/cmake/tests/ossp_uuid_lib_test.cc:6:5:
  error: 'uuid_make' was not declared in this scope; did you mean
  'uuid_type'?

      6 |     uuid_make(uuid, UUID_MAKE_V1);
        |     ^~~~~~~~~
        |     uuid_type

  make[1]: *** [CMakeFiles/cmTC_00946.dir/build.make:78:
  CMakeFiles/cmTC_00946.dir/ossp_uuid_lib_test.cc.o] Error 1

  make[1]: Leaving directory
  '/tmp/drogon-20230824-6746-jd94ug/build/cmaketest/CMakeFiles/CMakeTmp'

  make: *** [Makefile:127: cmTC_00946/fast] Error 2
```

**Comment by ken-matsui** [comment]
@an-tao Would you have any idea about this error?

**Comment by an-tao** [comment]
> @an-tao Would you have any idea about this error?

Hi, I'm new to brew. @rbugajewski Do you have any ideas?

**Comment by rbugajewski** [comment]
Is this maybe some kind of mismatch between libuuid and OSSP UUID?

**Comment by ken-matsui** [comment]
> Is this maybe some kind of mismatch between libuuid and OSSP UUID?

Do you mean two different libs are installed and caused a mismatch?

**Comment by rbugajewski** [comment]
libuuid could be installed (or both), but OSSP tests are run and libuuid is found (I don’t know why, maybe a bug, but I don’t have a better explanation for the error right now)?

**Comment by ken-matsui** [comment]
I see. Thank you!

**Pull request merged**
