### PR TITLE
Updated to Drogon 1.7.4 and some tweaks.

### PR DESCRIPTION
**Pull request by 0rangeFox**
Hey, I updated the Drogon to newest version and some little changes. About tests, wasn't successful for compile the project and got this error:
```bash
brew test drogon
==> Testing 0rangefox/drogon/drogon
==> /usr/bin/clang++ -std=c++14 /private/tmp/drogon-test-20220119-46125-139mvvb/drogon.cpp -o drogon -I/opt/homebrew/Cellar/drogon/1.7.4/include -L/opt/homebrew/Cellar/drogon/1.7.
Last 15 lines from /Users/0rangefox/Library/Logs/Homebrew/drogon/test.01.clang++:
      std::__1::__shared_ptr_pointer<sqlite3_stmt*, drogon::orm::Sqlite3Connection::execSqlInQueue(std::__1::basic_string_view<char, std::__1::char_traits<char> > const&, unsigned long, std::__1::vector<char const*, std::__1::allocator<char const*> > const&, std::__1::vector<int, std::__1::allocator<int> > const&, std::__1::vector<int, std::__1::allocator<int> > const&, std::__1::function<void (drogon::orm::Result const&)> const&, std::__1::function<void (std::exception_ptr const&)> const&)::$_3, std::__1::allocator<sqlite3_stmt> >::__on_zero_shared() in libdrogon.a(Sqlite3Connection.cc.o)
  "_sqlite3_last_insert_rowid", referenced from:
      drogon::orm::Sqlite3Connection::execSqlInQueue(std::__1::basic_string_view<char, std::__1::char_traits<char> > const&, unsigned long, std::__1::vector<char const*, std::__1::allocator<char const*> > const&, std::__1::vector<int, std::__1::allocator<int> > const&, std::__1::vector<int, std::__1::allocator<int> > const&, std::__1::function<void (drogon::orm::Result const&)> const&, std::__1::function<void (std::exception_ptr const&)> const&) in libdrogon.a(Sqlite3Connection.cc.o)
  "_sqlite3_open", referenced from:
      std::__1::__function::__func<drogon::orm::Sqlite3Connection::init()::$_1, std::__1::allocator<drogon::orm::Sqlite3Connection::init()::$_1>, void ()>::operator()() in libdrogon.a(Sqlite3Connection.cc.o)
  "_sqlite3_prepare_v2", referenced from:
      drogon::orm::Sqlite3Connection::execSqlInQueue(std::__1::basic_string_view<char, std::__1::char_traits<char> > const&, unsigned long, std::__1::vector<char const*, std::__1::allocator<char const*> > const&, std::__1::vector<int, std::__1::allocator<int> > const&, std::__1::vector<int, std::__1::allocator<int> > const&, std::__1::function<void (drogon::orm::Result const&)> const&, std::__1::function<void (std::exception_ptr const&)> const&) in libdrogon.a(Sqlite3Connection.cc.o)
  "_sqlite3_reset", referenced from:
      drogon::orm::Sqlite3Connection::execSqlInQueue(std::__1::basic_string_view<char, std::__1::char_traits<char> > const&, unsigned long, std::__1::vector<char const*, std::__1::allocator<char const*> > const&, std::__1::vector<int, std::__1::allocator<int> > const&, std::__1::vector<int, std::__1::allocator<int> > const&, std::__1::function<void (drogon::orm::Result const&)> const&, std::__1::function<void (std::exception_ptr const&)> const&) in libdrogon.a(Sqlite3Connection.cc.o)
  "_sqlite3_step", referenced from:
      drogon::orm::Sqlite3Connection::stmtStep(sqlite3_stmt*, std::__1::shared_ptr<drogon::orm::Sqlite3ResultImpl> const&, int) in libdrogon.a(Sqlite3Connection.cc.o)
  "_sqlite3_stmt_readonly", referenced from:
      drogon::orm::Sqlite3Connection::execSqlInQueue(std::__1::basic_string_view<char, std::__1::char_traits<char> > const&, unsigned long, std::__1::vector<char const*, std::__1::allocator<char const*> > const&, std::__1::vector<int, std::__1::allocator<int> > const&, std::__1::vector<int, std::__1::allocator<int> > const&, std::__1::function<void (drogon::orm::Result const&)> const&, std::__1::function<void (std::exception_ptr const&)> const&) in libdrogon.a(Sqlite3Connection.cc.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

And another question, what about making this official in Hombrew, so people don't have to do those commands.

### CODE REVIEW

**Comment by rbugajewski** [comment]
Thanks for the update. I will review it as soon as I’ll have some spare time.

In the meantime could you please remove the `.gitignore` as it is very bloated and I don’t think we need it here?

**Review by rbugajewski — CHANGES_REQUESTED** [review]
`.gitignore` should be removed and the test fixed before a merge.

**Comment by 0rangeFox** [comment]
> Thanks for the update. I will review it as soon as I’ll have some spare time.
> 
> In the meantime could you please remove the `.gitignore` as it is very bloated and I don’t think we need it here?

Sure, I just put in the case that we would make this official for Homebrew so that if someone wanted to contribute they wouldn't have to worry about the files when giving commit, as they would already be ignored.

Regarding the test, I am not an expert on Homebrew, but the problem I was having I think was related to this https://github.com/drogonframework/drogon/issues/1161. Later on, I will take a closer look at Homebrew and see how I can do the tests better, and so on, I will send or write something about my new results.

**Comment by ken-matsui** [comment]
I am closing this because this got stale.

**Pull request closed without merging**
